GET http://localhost:3000/mangas?title=anna

###

GET http://localhost:3000/mangas?title=man

### Post a la api rest
### Es Importante que las API estan abiertas a recibir todo typo de parametros
##EN el Body pero que puedan filtrar solo lo que necesitan
### Es decir que le puedo poner parametros de mas pero la API simplemento los va
### a Ignorar
POST http://localhost:3000/mangas
Content-Type: application/json

{
    "title": "The Godfather",
    "desc": "Lo mas raro que hay aqui",
    "img": "./A.jpg",
    "genre": ["Action"]
}

###

GET http://localhost:3000/mangas?title=the